### ISSUE TITLE
Using date field throws an error

### ISSUE THREAD

**Issue by Marco-Daniel** [toriphes/wp-graphql-ninja-forms#3]
When using the date field I get the following error in wp-graphql:

`debugMessage": "Abstract type FormField must resolve to an Object type at runtime for field FormToFormFieldConnection.nodes with value \"instance of WPGraphQL\\NinjaForms\\Model\\Field_Model\", received \"null\". Either the FormField type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function."`

**Comment by toriphes** [comment]
Hi @Marco-Daniel  thanks for the feedback.
It appears to be a problem with how wp graphql handles model values.

I just released version 0.1.3 which fixes this bug.

Please let me know if everything works fine.

**Comment by Marco-Daniel** [comment]
@toriphes Awesome, it's returning data now. Only the required field doesn't respect the settings, it always returns false.

**Comment by toriphes** [comment]
Maybe it's cache? I can't reproduce it locally

**Comment by Marco-Daniel** [comment]
I think you're right in that it was a caching issue or something like that. I can't reproduce it anymore. Thanks!
