### ISSUE TITLE
Plugin not compatible with wp-graphql 1.6 release

### ISSUE THREAD

**Issue by Marco-Daniel** [toriphes/wp-graphql-ninja-forms#5]
Hello,

When updating wp-graphql to 1.6 or higher errors occur. Disabling this plugin fixes it. 

Snippt from the wp-graphql slack channel:

> **Jason Bahl**  17 hours ago
> WPGraphQL for Ninja Forms also might need to update like WPGraphQL for Gravity Forms did:
> 
> **Jason Bahl**  17 hours ago
> https://github.com/harness-software/wp-graphql-gravity-forms/pull/137/files
> 
> **Jason Bahl**  17 hours ago
> specifically, Types that are only exposed within a Union or Interface will need to be updated to be eagerly loaded like so:
> 
> **Jason Bahl**  17 hours ago
> https://github.com/harness-software/wp-graphql-gravity-forms/pull/137/files#diff-5e3cb4912e2873eb15f02f75741d9310fa9a40a0cfba9f1f024ff66c2268c23aR25

**Comment by toriphes** [comment]
Hello @Marco-Daniel .
Thanks for the feedback and for the references.

I'll get deeper into the problem.

Anyway pull requests are welcome 😁

**Comment by Marco-Daniel** [comment]
I was messing around with it this morning but couldn't get it to work with wp-graphql 1.6.2. I either didn't understand where to add the `'eagerlyLoadType' => true`, or more work needs to be done to get it to work.

I did submit another pull request for a minor bug fix :wink:

**Comment by toriphes** [comment]
Just pushed the commit https://github.com/toriphes/wp-graphql-ninja-forms/commit/dd6456573a619080a83465050d1ae42a8eacd6c6 and it works on my env with wp-graphql 1.6.4 .

Can you test it?

**Comment by Marco-Daniel** [comment]
Just tested with wp-graphql 1.6.4 and seems to be working just fine!

**Comment by toriphes** [comment]
Thank you @Marco-Daniel !

i just released version [0.1.4](https://github.com/toriphes/wp-graphql-ninja-forms/releases/tag/0.1.4) which fixes this problem.
